# Generated by Django 5.1.4 on 2025-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customusermodel_draws_customusermodel_looses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='looses',
            new_name='losses',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='rating',
            field=models.IntegerField(db_index=True, default=1000),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
