# Generated by Django 5.1.4 on 2025-02-23 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_rename_looses_customusermodel_losses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_type', models.CharField(choices=[('Human', 'Human'), ('Orc', 'Orc'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf')], max_length=20)),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('strength', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
