# Generated by Django 5.1.4 on 2025-02-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_character'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='CharacterModel',
        ),
    ]
