# Generated by Django 5.1.4 on 2025-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_rename_character_charactermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
