# Generated by Django 5.1.4 on 2025-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_charactermodel_experience_charactermodel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='unused_points',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='agility',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='endurance',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='stamina',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='strength',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
